apiVersion: v1
kind: Pod
metadata:
  name: jmeter-pod
spec:
  containers:
    - name: jmeter
      image: justb4/jmeter:latest
      volumeMounts:
        - mountPath: /etc/testfile
          name: jemeter-files
  volumes:
    - name: jemeter-files
      hostPath:
        path: /run/desktop/mnt/host/c/home/neo/jmeterfiles # directory location on host
        type: Directory # this field is optional
