apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus-pod
      labels:
        app: prometheus
    spec:
      volumes:
        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: prometheus-pvc
        - name: prometheus-config
          configMap:
            name: prometheuscm
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
          volumeMounts:
            - name: prometheus-storage
              mountPath: /prometheus
            - name: prometheus-config
              mountPath: /etc/prometheus
              # prometheus.yml
              readOnly: true
          ports:
            - containerPort: 9090
