apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheusconfig-pv
  labels:
    name: prometheusconfig-pv
spec:
  storageClassName: ""
  claimRef:
    name: prometheusconfig-pvc
    namespace: default
  capacity:
    storage: 10Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /run/desktop/mnt/host/c/home/neo/prometheus-config/prometheus.yml
    type: "File"
