apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  labels:
    name: prometheus
spec:
  storageClassName: manual
  claimRef:
    name: prometheus-pvc
    namespace: default
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/c/home/neo/prometheus
