apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: default
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 20Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
